### ISSUE TITLE
MemoryError when evaluating existing estimates 

### ISSUE THREAD

**Issue by enisnazif** [sigsep/sigsep-mus-eval#19]
When attempting to perform evaluation of a single preseparated track, a large amount of memory seems to be allocated. 

Python(38705,0x7fffafd59340) malloc: *** mach_vm_map(size=380311055200256) failed (error code=3)
*** error: can't allocate region
*** set a breakpoint in malloc_error_break to debug
Traceback (most recent call last):
  File "CDAE_eval.py", line 36, in <module>
    mus.run(estimate_and_evaluate, subsets='dev')
  File "/usr/local/lib/python3.6/site-packages/musdb/__init__.py", line 452, in run
    total=len(tracks)
  File "/usr/local/lib/python3.6/site-packages/tqdm/_tqdm.py", line 930, in __iter__
    for obj in iterable:
  File "/usr/local/lib/python3.6/site-packages/musdb/__init__.py", line 448, in <lambda>
    estimates_dir
  File "/usr/local/lib/python3.6/site-packages/musdb/__init__.py", line 361, in _process_function
    user_results = user_function(track)
  File "CDAE_eval.py", line 20, in estimate_and_evaluate
    scores = museval.eval_mus_track(track, estimates, output_dir=DataConfig.JSON_PATH)
  File "/usr/local/lib/python3.6/site-packages/museval/__init__.py", line 349, in eval_mus_track
    mode=mode
  File "/usr/local/lib/python3.6/site-packages/museval/__init__.py", line 506, in evaluate
    references, estimates = pad_or_truncate(references, estimates)
  File "/usr/local/lib/python3.6/site-packages/museval/__init__.py", line 462, in pad_or_truncate
    mode='constant'
  File "/usr/local/lib/python3.6/site-packages/numpy/lib/arraypad.py", line 1377, in pad
    newmat = _append_const(newmat, pad_after, after_val, axis)
  File "/usr/local/lib/python3.6/site-packages/numpy/lib/arraypad.py", line 138, in _append_const
    return np.concatenate((arr, np.zeros(padshape, dtype=arr.dtype)),
MemoryError

The code I am using is as follows:

```
def estimate_and_evaluate(track):
    # generate our estimates (i.e, just load them)
    print(track)

    estimates = {
        'vocals': librosa.load(DataConfig.OUTPUT_PATH + track.name + '/vocals.wav', mono=False)[0],
        'bass': librosa.load(DataConfig.OUTPUT_PATH + track.name + '/bass.wav', mono=False)[0]
        'drums': librosa.load(DataConfig.OUTPUT_PATH + track.name + '/drums.wav', mono=False)[0],
        'accompaniment': librosa.load(DataConfig.OUTPUT_PATH + track.name + '/accompaniment.wav', mono=False)[0],
        other': librosa.load(DataConfig.OUTPUT_PATH + track.name + '/other.wav', mono=False)[0]
    }

    # Evaluate using museval
    scores = museval.eval_mus_track(track, estimates, output_dir=DataConfig.JSON_PATH)

    # print nicely formatted mean scores
    print(scores)

    # return estimates as usual
    return estimates

# initiate musdb
mus = musdb.DB(root_dir=DataConfig.MUSDB_PATH, is_wav=True)

# Use for dev purposes
mus.run(estimate_and_evaluate, subsets='dev')
```

**Comment by faroit** [comment]
1. yes we know about this. bss_eval v4 trades a faster computation for more memory usage. You can switch to bsseval v3 by turning on the framewise_filter. [See documentation](https://sigsep.github.io/sigsep-mus-eval/museval.metrics.html).
2. you should not evaluate the accompaniment along with the other 4 targets. Choose either ['vocals', 'accompaniment'] or ['vocals', 'bass', 'drums', 'other'] but not both as bsseval assumes a linear mixture of all sources.

**Comment by enisnazif** [comment]
Ah, I see, thank you. Typically how much RAM would be required in order to comfortably be able to evaluate the train / test sets for `['vocals', 'bass', 'drums', 'other']` using bsseval v4?
